baseURL = 'https://github.com/Jonas-du-bois/LabVeilleTech-hugo'
languageCode = 'fr-fr'
title = 'LabVeilleTech-JonasDuBois'
theme = 'hugo-minimal-black'

[params]
    author = "Jonas Du Bois"
    description = "SIte pour le cours de LabVeilleTech"

